name: dart_sdk
publish_to: none
environment:
  sdk: ^3.5.0
workspace:
  - pkg/_fe_analyzer_shared
  - pkg/_macros
  - pkg/analyzer
  - pkg/analyzer_utilities
  - pkg/heap_snapshot
  - pkg/linter
  - pkg/js
  - pkg/macros
  - pkg/meta
  - pkg/vm_service
  - pkg/vm_service/test/test_package
  - pkg/vm_service_protos

dependency_overrides:
  args:
    path: third_party/pkg/args
  async:
    path: third_party/pkg/async
  boolean_selector:
    path: third_party/pkg/boolean_selector
  checks:
    path: third_party/pkg/test/pkgs/checks
  cli_util:
    path: third_party/pkg/cli_util
  collection:
    path: third_party/pkg/collection
  convert:
    path: third_party/pkg/convert
  coverage:
    path: third_party/pkg/coverage
  crypto:
    path: third_party/pkg/crypto
  file:
    path: third_party/pkg/file/packages/file
  fixnum:
    path: third_party/pkg/fixnum
  frontend_server_client:
    path: third_party/pkg/webdev/frontend_server_client
  glob:
    path: third_party/pkg/glob
  http:
    path: third_party/pkg/http/pkgs/http
  http_multi_server:
    path: third_party/pkg/http_multi_server
  http_parser:
    path: third_party/pkg/http_parser
  io:
    path: third_party/pkg/io
  lints:
    path: third_party/pkg/lints
  logging:
    path: third_party/pkg/logging
  markdown:
    path: third_party/pkg/markdown
  matcher:
    path: third_party/pkg/matcher
  mime:
    path: third_party/pkg/mime
  node_preamble:
    path: third_party/pkg/node_preamble
  package_config:
    path: third_party/pkg/package_config
  path:
    path: third_party/pkg/path
  pool:
    path: third_party/pkg/pool
  protobuf:
    path: third_party/pkg/protobuf/protobuf
  pub_semver:
    path: third_party/pkg/pub_semver
  shelf:
    path: third_party/pkg/shelf/pkgs/shelf
  shelf_packages_handler:
    path: third_party/pkg/shelf/pkgs/shelf_packages_handler
  shelf_static:
    path: third_party/pkg/shelf/pkgs/shelf_static
  shelf_web_socket:
    path: third_party/pkg/shelf/pkgs/shelf_web_socket
  source_map_stack_trace:
    path: third_party/pkg/source_map_stack_trace
  source_maps:
    path: third_party/pkg/source_maps
  source_span:
    path: third_party/pkg/source_span
  stack_trace:
    path: third_party/pkg/stack_trace
  stream_channel:
    path: third_party/pkg/stream_channel
  string_scanner:
    path: third_party/pkg/string_scanner
  term_glyph:
    path: third_party/pkg/term_glyph
  test:
    path: third_party/pkg/test/pkgs/test
  test_api:
    path: third_party/pkg/test/pkgs/test_api
  test_core:
    path: third_party/pkg/test/pkgs/test_core
  test_reflective_loader:
    path: third_party/pkg/test_reflective_loader
  typed_data:
    path: third_party/pkg/typed_data
  watcher:
    path: third_party/pkg/watcher
  web:
    path: third_party/pkg/web
  web_socket:
    path: third_party/pkg/http/pkgs/web_socket
  web_socket_channel:
    path: third_party/pkg/web_socket_channel
  webkit_inspection_protocol:
    path: third_party/pkg/webkit_inspection_protocol
  yaml:
    path: third_party/pkg/yaml
