name: analyzer_utilities
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  analyzer: any
  path: any
  test: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  lints: any
